### ISSUE TITLE
'matlab=matlab_wrapper.MatlabSession() 'error

### ISSUE THREAD

**Issue by shuxp** [mrkrd/matlab_wrapper#22]
when I run 'matlab=matlab_wrapper.MatlabSession() ', I got this error:
' RuntimeError: It seem that you are using 64bit version of Python, but there's no matching MATLAB installation in /usr/local/MATLAB/R2015b:/usr/local/MATLAB/R2015b:/bin/glnxa64.'
Anyone can help me?thanks.

**Comment by mrkrd** [comment]
> when I run 'matlab=matlab_wrapper.MatlabSession() ', I got this error:
> ' RuntimeError: It seem that you are using 64bit version of Python, but there's no matching MATLAB installation in /usr/local/MATLAB/R2015b:/usr/local/MATLAB/R2015b:/bin/glnxa64.'
> Anyone can help me?thanks.

What's the value of MATLABROOT env variable?  Is it
"/usr/local/MATLAB/R2015b:/usr/local/MATLAB/R2015b:/bin/glnxa64"?

If yes, then you could fix it by setting it to a single directory
(Matlab root directory).

Otherwise, please check the docstring of `matlab_wrapper.MatlabSession`
and provide info about your setup:
https://github.com/mrkrd/matlab_wrapper/blob/master/CONTRIBUTING.rst#reporting-issues

Cheers,
Marek
