### ISSUE TITLE
Error: 'Matlab must be run with full administrator rights' 

### ISSUE THREAD

**Issue by alanmc979** [mrkrd/matlab_wrapper#24]
I am using the wrapper to use Matlab's DAQ Toolbox in Python. I have been getting this error message when I try to register my device (DT9816 ). I found an answer in this link https://www.mathworks.com/matlabcentral/answers/99879-why-does-daqregister-fail-on-windows-vista-and-windows-7-with-uac-enabled which states that I should run Matlab as administrator but I will like to know if there is a way to run the wrapper and use Matlab as administrator. 
![img_2469](https://user-images.githubusercontent.com/26907780/30131331-405deedc-9301-11e7-8422-9f51ba596fd2.jpg)

**Comment by mrkrd** [comment]
Hi Alan,

This issue is not really related to matlab_wrapper but rather to
permissions on Windows.

I really don't know much about Windows, but I guess that giving
administrator privileged to Python would "fix" it in a similar way as it
did with MATLAB.

It's probably not the most secure solution, but for a better one you'll
need to research for yourself how Windows permissions work.

Cheers,

Marek

**Comment by alanmc979** [comment]
I solved it, I just needed to open Python as an administrator in order to use the DAQ toolbox. I thought it was the wrapper making the error.

Thank you, Marek
