### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by kitchenknif** [mrkrd/matlab_wrapper#3]
Is there anything serious stopping Python3 support?
I've run into some standard string handling issues, but haven't really looked into the problem...

**Comment by mrkrd** [comment]
Hi, because I do not have time to work on Python 3 support, I started to recommend the official MATLAB engine for Python that comes with MATLAB 2015a.  It supports Python version 2.7, 3.3, and 3.4 and might a viable and well supported package in the long run. Time will show.

matlab_wrapper should not stop working suddenly, but it's not actively developed any more.

[1] http://www.mathworks.com/help/matlab/matlab-engine-for-python.html

**Comment by toddrjen** [comment]
The problem with the matlab engine for Python is that it usually takes a year or more for MATLAB to support the latest version of Python.  Python 3.5 was released in September 2015, but MATLAB R2016a (released in March 2016) doesn't support it, and there is no indication from the prerelease changelog that R2016b will support it either.  So a third-party solution is still very much needed.

**Comment by mrkrd** [comment]
Python 3 will probably not happen for this library.  I would prefer to start a new one just for Python 3 (matlab_wrapper3), because it would not have to be backward compatible, and there are some things I would like to change in a backward incompatible manner (check TODO.org).

I'm not working with Matlab at the moment and have only a little time to maintain matlab_wrapper, so there is no specific time line for matlab_wrapper3.
